POST https://node-do-zero-marcos.onrender.com/videos
Content-Type: application/json

{
    "title": "Vídeo Python",
    "description": "Este é o primeiro vídeo.",
    "duration": 180
}

###

GET https://node-do-zero-marcos.onrender.com/videos

###

PUT https://node-do-zero-marcos.onrender.com/videos
Content-Type: application/json

{
    "title": "Vídeo Python",
    "description": "Este é o segundo vídeo.",
    "duration": 180
}

###

DELETE https://node-do-zero-marcos.onrender.com/videos